### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by brannondorsey** [echicken/node-ax25#2]
Hey there,

Thanks for your work on this project. I just wanted to check-in on the current status. The note in the README suggests to use the new es6rewrite branch as well as the new KISS module you've been working on, but after playing around with both it seems that they are pretty inoperable at the moment. Am I missing something? I'm looking to write some ax25 tools in node and it would be great to rely on some of the stuff you have already written as a foundation...

I've gotten the old `master` version to work with an old version of Node, but I was hoping maybe you could advise as to the health of this project, or what you would recommend moving forward?

Thanks!

**Comment by echicken** [comment]
The last time I checked, the new KISS module worked properly with my TNCs.
The es6rewrite branch is only useful for encoding and decoding packets, not
for carrying on a full session at the moment.  You could do stuff with UI
frames (eg. APRS) or monitor traffic, that's about it.

That said, I definitely do not recommend using the old version and I have
zero interest in supporting it.  It's bad and I feel bad for writing it.

Health-wise the project is still alive but it only captures my interest
every so often.  I haven't forgotten about it or abandoned it.
Connected-mode / session stuff will be a chore to write, so I've been
putting it off.

If you're having a specific problem with the new stuff, I can take a look
and see what I may need to fix.  If you need full sessions, I / we could
try to do some work on that in the near future.  Happy to chat some more
about it.

**Comment by brannondorsey** [comment]
Gotcha! Thanks for the reply and sorry to drag my feet in getting back to you. You are indeed correct that the es6rewrites branch of node-ax25 does work with the kiss-tnc module. I can't remember now what was causing the issue I was having, but your software wasn't to blame.

As for the use case, AX.25 UI frames work work for my purposes now. Sessions would be fun in the future but no worries if that isn't a priority now. I've actually used this lib to create a small library/application on top of AX.25 which supports digital signatures and compression, called [chattervox](https://github.com/brannondorsey/chattervox).

Anyway, just wanted to say thanks for making these tools and sharing them with others :+1:

**Comment by hoche** [comment]
I just did a bunch of work on the session object and checked in my initial take on it, but I had a bunch of travel come up and haven't had a chance to do much more than the most basic of tests on it. Schedule permitting I'll be getting back to it around mid-Oct. My hope is to have a functioning session by the end of next month as well as a rudimentary test suite.
